# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 10:04
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('adapt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
