# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adapt', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_data',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 18, 9, 54, 16, 318636, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.ImageField(default=datetime.datetime(2016, 7, 18, 9, 54, 26, 566053, tzinfo=utc), help_text='150x150px', upload_to='img/', verbose_name='\u0417\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f'),
            preserve_default=False,
        ),
    ]
