# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('adapt', '0004_auto_20160718_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=200)),
                ('service_img', models.ImageField(help_text='150x150px', upload_to='img/', verbose_name='\u0417\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f')),
                ('service_data', models.DateTimeField()),
                ('service_text', tinymce.models.HTMLField()),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
