# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adapt', '0006_auto_20161017_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '\u041f\u043e\u0441\u043b\u0443\u0433\u0438', 'verbose_name_plural': '\u041f\u043e\u0441\u043b\u0443\u0433\u0438'},
        ),
    ]
