# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adapt', '0007_auto_20161017_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': '\u0414\u0430\u043d\u0456', 'verbose_name_plural': '\u0414\u0430\u043d\u0456'},
        ),
    ]
